### PR TITLE
Tyler/new workshop fields

### PR DESCRIPTION
**Pull request by tcorrellpsu**
Added 3 new workshop fields

### CODE REVIEW

**Comment by rsquared226** [comment]
Looks great! Is there a way to make it an array of download links though? Some workshops have more than 1

**Comment by tcorrellpsu** [comment]
> Looks great! Is there a way to make it an array of download links though? Some workshops have more than 1

This is a good idea. I have somewhat of an idea of how to do this but it might not work. What should I change the Type of  ws_download_links in mySQL to be then? It's currently varchar(400).

**Comment by rsquared226** [comment]
hmm @stan29308 what do you think

**Comment by sawyer-nye** [comment]
Any update on this?

**Comment by stan29308** [comment]
We can either just delimit each url with a | or some other character, or we can make another set of tables with one holding URLs and another for holding one to many connections

**Comment by rsquared226** [comment]
> delimit each url with a | or some other character

That's smart we should do that

**Review by rsquared226 — APPROVED** [review]

**Comment by sawyer-nye** [comment]
Prof Shaffer from 431W would not be very happy with using a delimiter

**Comment by stan29308** [comment]
Never took 431W so can't relate. But on a serious note, I don't think the downsides of delimiter would affect us all that much. Uniqueness isn't a concern or can be fixed in code and same with searching. We also have nothing referencing them because the url's are standalone and unique to the particular workshop.

But I think Sawyer is probably right. If we want to maintain first normal form, it wouldn't be that hard, we can always just create a new table just for workshop links.
This would look like:
URL ID | Event ID | URL
0 | 4 | hackpsu.org
1 | 4 | tutorial.org
2 | 3 | python.org

**Review by stan29308 — APPROVED** [review]

**Comment by rsquared226** [comment]
Either way works for me, your call @stan29308

**Comment by tcorrellpsu** [comment]
Sounds better than just creating an array. Stan and I will work on it. Should be a good learning experience.

**Comment by tcorrellpsu** [comment]
I created a new sql table called URLS to hold download links as well as the files for changes from my commit message. Stan says he'll work on the implementation of the relationship between download links and event objects in the coming days. Very sorry for the delay. I did not expect this much of a project when I started out.

**Comment by stan29308** [comment]
Should be good to go now, changed spacing from 4 to 2 to please the linter and changed file names to be singular 'url' from plural 'urls'. Since there is no well defined way to do arrays for post requests that I could find and verify with testing, urls to be linked to an event will still be a string delimited with a '|'. In the backend, we will split the string and create a separate entry into an sql table for each url linked to some event.

**Pull request merged**
