### PR TITLE
updating docs

### PR DESCRIPTION
**Pull request by jdurrell**
just updating comments, no new code here

### CODE REVIEW

**Comment by tcorrellpsu** [comment]
everything looks good. Was user address added more recently or was this just forgotten for a while (just curious)?

**Comment by jdurrell** [comment]
User address has been there since Fall, but I guess it just wasn't added to the documentation

**Comment by tcorrellpsu** [comment]
gotcha

**Review by rsquared226 — APPROVED** [review]

**Review by tcorrellpsu — APPROVED** [review]
looks good

**Pull request merged**
